### ISSUE TITLE
This looks awesome.

### ISSUE THREAD

**Issue by sfkaos** [HarrisRobin/medium-scraper#1]
How do I use it?

**Comment by HarrisRobin** [comment]
@sfkaos I built this a while ago before medium had an API. I would look into their API first and see if that can suit your needs:
https://github.com/Medium/medium-api-docs

Otherwise, to run it simply modify line 59 with the medium URL you'd like to scrape and it will return all the posts. (this should be achievable via the API, which is 100x better).

**Comment by sfkaos** [comment]
Actually, Medium only has a publishing API. There is no API to scrape data.

On Wed, Mar 23, 2016 at 1:27 PM, Harris Robin Kalash <
notifications@github.com> wrote:

> @sfkaos <https://github.com/sfkaos> I built this a while ago before
> medium had an API. I would look into their API first and see if that can
> suit your needs:
> https://github.com/Medium/medium-api-docs
>
> Otherwise, to run it simply modify line 59 with the medium URL you'd like
> to scrape and it will return all the posts. (this should be achievable via
> the API, which is 100x better).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/HarrisRobin/medium-scraper/issues/1#issuecomment-200530645>
>



-- 
Cheers,
Win Raguini
703.966.9682 | @sfkaos

**Comment by HarrisRobin** [comment]
@sfkaos i see. have you tried running this with `node index.js` after modifying the url on line 59?
